
image:
  repository: us-central1-docker.pkg.dev/terraform-gke-gpt/gke-repo/gpt
  tag: latest

replicaCount: 1

containerPort: 8000

service:
  type: LoadBalancer
  port: 8000
  targetPort: 8000

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env: {}
